{% set name = "tudat-resources" %}
  {% set version = "2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tudat-team/{{ name }}.git
  git_rev: b466a30508500d7ceb0932ff6880f2129c0ba378

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: 1   # [win]
  number: 1   # [not win]

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make                             # [unix]
    - curl

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - curl
  source_files:
    - test/test_binary
  commands:
    - cd ./test/test_binary
    - bash run_binary_test.sh

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A resource manager aimed towards astrodynamics and space research.

extra:
  recipe-maintainers:
    - geoffreygarrett


