{% set name = "tudat-resources" %}
  {% set version = "1.2.1.dev4" %}
  {% set build = "0" %}
  {% set git_rev = "1.2.1.dev4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tudat-team/{{ name }}.git
  git_rev: {{ git_rev }}

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: {{ build }}

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - cmake
    - make # [unix]

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A resource manager aimed towards astrodynamics and space research.

extra:
  recipe-maintainers:
    - geoffreygarrett
    - DominicDirkx


