github:
  user_or_org: tudat-team

channels:
  targets:
   - [tudat-team, dev]

conda_forge_output_validation: true

provider:
  linux: azure
  osx: azure
  win: azure
  linux_ppc64le: None
  linux_aarch64: None

build_platform:
  osx_arm64: osx_64
test_on_native_only: true

appveyor:
  secure:
    BINSTAR_TOKEN: 162vzpI6vqJ8dKusUseZODe+9BmwpKFBasmD7/L6rgHeqH1mMcfUbrbxdzjjaFE9

azure:
  # flag for forcing the building all supported providers
  force: True
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: True